#
#excluded:
#  - Carthage
#  - Pods
#  - R.generated.swift
#
#
#disabled_rules:
#  - trailing_whitespace
#  - force_cast
#  - switch_case_alignment
#  - redundant_string_enum_value
#  - closure_parameter_position
#  - identifier_name
#  - vertical_whitespace
#  - colon
#  - comment_spacing
#  - for_where
#  - function_body_length
#  - redundant_optional_initialization
#  - cyclomatic_complexity
#  - empty_parentheses_with_trailing_closure
#  - type_name
#line_length: 500

excluded:
   - Carthage
   - Pods
   - R.generated.swift
   
disabled_rules:
   - cyclomatic_complexity
   - identifier_name
   - type_name
   

line_length: 500
